name: bot-miz
services:
  miz:
    image: oven/bun:latest
    container_name: bot-miz
    restart: always
    working_dir: /app
    environment:
      TZ: Asia/Shanghai
    command: ["bun", "run", "scripts/start-docker.ts"]
    volumes:
      - .:/app
    networks:
      - diana

networks:
  diana:
    external: true
