[miz.gateway]
url = "ws://napcat-miz:3000"

[miz.postgresql]
url = "http://postgresql:5432"

[miz.network]
proxyUrl = "http://clash:7890"

[miz.vtb]
dynamicApiUrl = "http://rsshub:1200/bilibili/user/dynamic/"
