[miz.gateway]
url = ""
accessToken = ""

[miz.postgresql]
url = ""
database = ""
username = ""
password = ""

[miz.naplink]
logLevel = ""
connectTimeoutMs = 0
pingIntervalMs = 0
apiTimeoutMs = 0
apiRetries = 0
reconnectMaxAttempts = 0

[miz.plugins]
commandPrefix = ""
directory = ""

[miz.network]
proxyUrl = ""

[miz.bilibili]
cookie = ""

[miz.ff14]
priceAlertEnabled = true
priceAlertCron = ""
maxListingCount = 0
itemSearchApiUrl = ""
marketApiUrl = ""

[miz.wallpaper]
enabled = true
cron = "0 7 * * *"
apiUrl = ""
imageBaseUrl = ""

[miz.news]
enabled = true
cron = "*/5 * * * *"
groupIds = []
apiUrl = ""

[miz.reminder]
enabled = true
cron = "* * * * *"
batchSize = 20
manageWhitelistUserIds = []

[miz.schedule]
enabled = true
cron = "* * * * *"
reminderMinutes = 30
batchSize = 20
manageWhitelistUserIds = []

[miz.broadcast]
whitelistUserIds = []

[miz.video]
enabled = true
whitelistUserIds = []
downloadDirectory = "/temp"
napcatMediaDirectory = "/app/media"
ytDlpLinuxPath = "tools/yt-dlp"
ytDlpWindowsPath = "tools/yt-dlp.exe"
ffmpegLinuxPath = "tools/ffmpeg"
ffmpegWindowsPath = "tools/ffmpeg.exe"
updateCron = "0 0 * * *"

[miz.vtb]
enabled = true
cron = "*/3 * * * *"
userApiUrl = ""
cardApiUrl = ""
liveApiUrl = ""
dynamicApiUrl = ""
nameSyncCron = "0 0 * * 0"
syncWhitelistUserIds = []
subscriptionWhitelistUserIds = []
